
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
version: 3.4.3

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: ['.c9']

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

url: https://datasf.org

paginate: 5
paginate_path: "/blog/:num/"

collections:
  team_members:
    output: true
  resource_topics:
    output: true
    permalink: '/resources/:title/'

defaults:
  -
    scope:
      path: ""
      type: "team_members"
    values:
      sitemap: false
      layout: "team-member"
      _comments:
        instructor: To indicate whether a Data Academy instructor, select either Yes, No or Alum (if former instructor)
  -
    scope:
      type: "resource_topics"
    values:
      _comments:
        title: Give the collection of resources a handy name
        description: A short description used in html metadata and on lists where a summary is provided.
        tags: (optional) Keywords used by the resources search
        resources_list: List of the related resources and their relevant links
        name: Name of the resource
        post_date: The date the resource was first made available
        resource_type: A fixed list of generalized resource types
        links: One or more links to the resource
        link: The url of the resource
        media_type: The type of link provided as context to the user when downloading or opening a link from the website
  -
    scope:
      path: "academy"
    values:
      layout: "course"
      index: "academy"
      hidden: true
      subnav: true
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "blog-post"
  -
    scope:
      path: ""
      type: "resource_topics"
    values:
      layout: "resource-topic"
      index: "resources"
      subnav: true
  -
    scope:
      path: "showcase"
    values:
      layout: "project-story"
      index: "showcase"
      toc: true
      hidden: true
      subnav: true
    
      
# Site settings
title: DataSF
email: datasf@sfgov.org
description: "Our mission is to empower use of the City and County of San Francisco's data. Our core product is SF OpenData, the official open data portal."
locale: en_US

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 245f7b
  secondary: 6dbce2  
  secondary-dark: 333333
  tertiary: 408bae
  accent: 7dd191

owner:
  name: DataSF
  email: 
  twitter: datasf
  google:
    ad-client: 
    ad-slot: 
    plus:
  bio: 
  gravatar:  # 160x160 px image for author byline
disqus-shortname:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/datasf
  - title: stack-overflow
    url: http://opendata.stackexchange.com/search?q=san+francisco
  - title: github 
    url: http://github.com/datasf

subjects:
  - Analysis
  - Visualization
  - Mapping
  - Information Design
  - Data Management
  - Excel
  - Tableau
  - Process Improvement

instructors:
  - Yes
  - No
  - Alum
 
series:
  - Excel
  - Tableau
  
resource_types:
  - Document
  - Guide
  - Toolkit
  - Template
  - Video
  - Spreadsheet
  - Research
  - One Pager
  
media_types:
  - Excel
  - Word
  - Google Doc
  - Google Spreadsheet
  - PDF
  - Link
  
audiences:
  - Data Coordinator
  - Data Publisher
  - DataSF Staff