# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /:categories/:title/

url: http://datasf.org
defaultbranch: gh-pages

paginate: 3
paginate_path: "blog/page/:num/"

defaults:
  -
    scope:
      path: "resources"
      type: "posts"
    values:
      hidden: true

# Site settings
title: DataSF
email: your-email@domain.com
description: "DataSF is..."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 245f7b
  secondary: 6dbce2  
  secondary-dark: 333333

owner:
  name: DataSF
  email: 
  twitter: datasf
  google:
    ad-client: 
    ad-slot: 
    plus:
  bio: 
  gravatar:  # 160x160 px image for author byline
disqus-shortname:

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/datasf
  - title: stack-overflow
    url: http://opendata.stackexchange.com/search?q=san+francisco
  - title: github 
    url: http://github.com/datasf

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

prose:
  siteurl: "http://datasf.github.io/datasf-website"
  media: "uploads"
  metadata:
    _posts/resources:
      - name: "category"
        field:
          element: "hidden"
          value: "resource"
      - name: "tags"
        field:
          element: "select"
          label: "Select Resource Category"
          options: "http://datasf.github.io/datasf-website/api/jsonp/tags.json?callback=tagsCallback"
          alterable: true
          placeholder: "Choose"
    _posts/blog:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "date"
        field:
          element: "text"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          options: http://datasf.github.io/datasf-website/api/jsonp/authors.json?callback=authorsCallback
      - name: "thumbnail"
        field:
          element: "text"
      - name: "description"
        field:
          element: "text"